### PR TITLE
Apply HybridDog's changes to fix positioning

### LINKED ISSUE #2: Import some fixes from HybridDog fork
Fork located at https://github.com/HybridDog/painting

Oh boy, but that changelog comments...

Related:
https://forum.minetest.net/viewtopic.php?p=229513#p229513

### PR DESCRIPTION
**Pull request by AntumDeluge**
Ports changes from [HybridDog's commit](https://github.com/HybridDog/painting/commit/090f809de3e4425178b31b182752b81acc1e2886) to fix paint positioning.

Closes: #2

### CODE REVIEW

File: init.lua [hunk 1]
```diff
@@ -189,9 +189,8 @@ minetest.register_entity("painting:paintent", {
 
 		--get player eye level
 		--see player.h line 129
-		local ppos = puncher:getpos()
-
-		ppos.y = ppos.y + 1.625
+		local ppos = vector.add(puncher:getpos(), puncher:get_eye_offset())
```
Comment (SmallJoker) [inline init.lua]: should be `get_pos()` since 0.4.16.

Comment (AntumDeluge) [reply init.lua]: I'm surprised I didn't catch that. Will get it updated.

Comment (AntumDeluge) [reply init.lua]: Done in dc43218
